### ISSUE TITLE
Queue spot reset after map change and/or map restart ?

### ISSUE THREAD

**Issue by dazurn** [Melodeiro/minqlx-plugins_mattiZed#2] opened 2016-08-28 02:34 UTC
Hi there,

There seems to be issues with players losing there queue spot after map change or map restart, any other reports? It doesn't seem to happen systematically though :(

My server is a CA server btw.

zurn

**Comment by Melodeiro** [comment] 2016-08-28 13:18
Hello, thanks for your report!

Is their tag are changing to (s)? What do you seee in !q? Do they pressing "spectate" in game menu after reloading map (they should press join instead)? Does just some people losing position or all whole queue being lost? Anything interesting in the logs?

Players should be removed from queue only in certain cases: leaving from spectators in any ways, using !afk command and pressing "spectate" button. It might be visual glitch, in this case, !q command should show the actual queue.

And you are the first who reported.

**Comment by dazurn** [comment] 2016-08-31 15:13
Here's what I recevied from a player. Hope that helps

10:22 AM - _Null: ive reproduced it, all you have to do is renamed your steam name via settings while you are in queue, then once the same/different map loads (not a map_restart though) the current queue will be empty but the spectators will still ahve (1) or (2) w/e queue slot they were in previously
10:23 AM - _Null: it also screws up the teamsize, the teamsize could be set to 4, but for some reason some ppl in the queue will be auto joined
10:23 AM - _Null: havnt figured that one out yet

**Comment by 00-rcb** [comment] 2016-08-31 15:50
Hello Melodeiro,

Thank you for creating this useful minqlx plugin! To elaborate further on the issue zurn mentioned; I'll describe a quick summary of the observed behavior, steps to reproduce, and one possible solution.

The bug occurs after a map load when a player who is currently in-queue renames via steam settings prior to the map load. To reproduce the bug, try the following:

1) Have a couple players in-game, and a couple in-queue.
2) Begin a game.
3) Have one player in-queue rename via steam settings.
4) Cause a map load either by callvote, finishing a game or forcing a map change with !map <name> (map_restart will not cause the bug).

The bug should be noticeable at this point, spectators who were previously in-queue will still have the queue slot tag prepended to their name, but executing "!q" will yield differing results than expected, and will most likely be empty. To help clarify I'll describe a typical scenario.

Suppose you had a Clan Arena game like this:

Red (2/2):
    Player-1
    Player-2
Blue (2/2):
    Player-3
    Player-4

Two more players connect and join the queue:

Spec:
    (1) Player-5
    (2) Player-6

Executing "!q" yields:
Queue >> (1) Player-5 (2) Player-6

One of the players currently in-queue renames via steam settings:
Player-6 renames to BugIt-Player-6

Executing "!q" yields:
Queue >> (1) Player-5 (2) Player-6

Executing "!map campgrounds" causes the map to load, and the scoreboard will look like this:

Red (2/2):
    Player-1
    Player-2
Blue (2/2):
    Player-3
    Player-4
Spec:
    (1) Player-5
    (2) BugIt-Player-6

Executing "!q" yields nothing in-queue:
Queue >> 

A possible solution would be to use the SteamID64 to store within the _queue array, instead of the "player" instance itself. I suspect when a player renames via steam settings, a new player instance is created which is causing the issue, but I could be wrong, I have not done any debugging to narrow down the cause. Hopefully this describes the bug well enough, many servers benefit from your plugin!

**Comment by Melodeiro** [comment] 2016-09-02 19:30
Hi!
Thanks for your reports and feedback!
I have tried to reproduce the bug with the bots, but the only problem i received is the wrong !q output:

> Executing "!q" yields:
> Queue >> (1) Player-5 (2) Player-6

After the new map loading it remains the same, and queue still works as it should. It pushes me into the game even with a different name. Also i have tested if "player" instance is changing, but in my case its not. What is in your qlx_plugins guys?

**Comment by dazurn** [comment] 2016-09-02 19:36
set qlx_plugins "DEFAULT,balance,irc,checkplayers,branding,midair,aliases,queue,servers,ips,votemanager,vote,commlink,mybalance,fun,player_info"

**Comment by Melodeiro** [comment] 2016-09-04 14:32
Just tried to reproduce again with real players, 3 in red team, 3 in blue, and 2 in queue. Also with your plugins. Still working as it should with only visual bug. Can you give me your cfg file (factory file, running parameters and .cfg file)? Maybe i can reproduce the bug that way. Just don't forget to remove all passwords!

**Comment by Melodeiro** [comment] 2016-11-27 00:39
Sorry for a big delay. I have found an idea for fix, but im not sure. Can you test if a bug still occurs with this version?

**Comment by Melodeiro** [comment] 2016-11-27 00:54
There is a version with some logging. If it will not help, maybe logs will tell me something.
**Upd:** a bit more logging http://pastebin.com/W4v4nAN6

**Comment by dazurn** [comment] 2016-12-17 00:51
I'll try it, I've been getting more report of the bug. Thanks for the effort :)

**Comment by dazurn** [comment] 2016-12-17 13:10
The plugin seems to crash on load

(08:03:20) [INFO @ minqlx._configure_logger] ============================= minqlx run @ 2016-12-17 08:03:20.025037 =============================
(08:03:20) [INFO @ minqlx.late_init] Loading preset plugins...
(08:03:20) [INFO @ minqlx.load_plugin] Loading plugin 'ban'...
(08:03:20) [INFO @ minqlx.load_plugin] Loading plugin 'branding'...
(08:03:20) [INFO @ minqlx.load_plugin] Loading plugin 'servers'...
(08:03:20) [INFO @ minqlx.load_plugin] Loading plugin 'motd'...
(08:03:20) [INFO @ minqlx.load_plugin] Loading plugin 'silence'...
(08:03:20) [INFO @ minqlx.load_plugin] Loading plugin 'checkplayers'...
(08:03:20) [INFO @ minqlx.load_plugin] Loading plugin 'permission'...
(08:03:20) [INFO @ minqlx.load_plugin] Loading plugin 'workshop'...
(08:03:20) [INFO @ minqlx.load_plugin] Loading plugin 'aliases'...
(08:03:20) [INFO @ minqlx.load_plugin] Loading plugin 'mybalance'...
(08:03:20) [INFO @ minqlx.load_plugin] Loading plugin 'essentials'...
(08:03:20) [INFO @ minqlx.load_plugin] Loading plugin 'clan'...
(08:03:20) [INFO @ minqlx.load_plugin] Loading plugin 'midair'...
(08:03:20) [INFO @ minqlx.load_plugin] Loading plugin 'commlink'...
(08:03:20) [INFO @ minqlx.commlink.__init__] Connecting to 158.69.209.167...
(08:03:20) [INFO @ minqlx.load_plugin] Loading plugin 'vote'...
(08:03:20) [INFO @ minqlx.load_plugin] Loading plugin 'names'...
(08:03:20) [INFO @ minqlx.load_plugin] Loading plugin 'fun'...
(08:03:20) [INFO @ minqlx.load_plugin] Loading plugin 'log'...
(08:03:20) [INFO @ minqlx.load_plugin] Loading plugin 'player_info'...
(08:03:20) [INFO @ minqlx.load_plugin] Loading plugin 'balance'...
(08:03:20) [INFO @ minqlx.load_plugin] Loading plugin 'irc'...
(08:03:20) [INFO @ minqlx.irc.__init__] Connecting to 158.69.209.167...
(08:03:20) [INFO @ minqlx.load_plugin] Loading plugin 'votemanager'...
(08:03:20) [INFO @ minqlx.load_plugin] Loading plugin 'plugin_manager'...
(08:03:20) [INFO @ minqlx.load_plugin] Loading plugin 'queue'...
(08:03:20) [ERROR @ minqlx.queue.log_exception] Traceback (most recent call last):
(08:03:20) [ERROR @ minqlx.queue.log_exception]   File "minqlx.zip/minqlx/_core.py", line 338, in load_plugin
(08:03:20) [ERROR @ minqlx.queue.log_exception]     module = importlib.import_module("{}.{}".format(plugins_dir, plugin))
(08:03:20) [ERROR @ minqlx.queue.log_exception]   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
(08:03:20) [ERROR @ minqlx.queue.log_exception]     return _bootstrap._gcd_import(name[level:], package, level)
(08:03:20) [ERROR @ minqlx.queue.log_exception]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
(08:03:20) [ERROR @ minqlx.queue.log_exception]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
(08:03:20) [ERROR @ minqlx.queue.log_exception]   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
(08:03:20) [ERROR @ minqlx.queue.log_exception]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
(08:03:20) [ERROR @ minqlx.queue.log_exception]   File "<frozen importlib._bootstrap_external>", line 661, in exec_module
(08:03:20) [ERROR @ minqlx.queue.log_exception]   File "<frozen importlib._bootstrap_external>", line 767, in get_code
(08:03:20) [INFO @ minqlx.irc.run] Disconnected from SIN-NET. Reconnecting in 30 seconds...
(08:03:20) [ERROR @ minqlx.queue.log_exception]   File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
(08:03:20) [ERROR @ minqlx.queue.log_exception]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
(08:03:20) [ERROR @ minqlx.queue.log_exception]   File "./minqlx-plugins/queue.py", line 358
(08:03:20) [ERROR @ minqlx.queue.log_exception]     self._queue = []
(08:03:20) [ERROR @ minqlx.queue.log_exception]                    ^
(08:03:20) [ERROR @ minqlx.queue.log_exception] IndentationError: unindent does not match any outer indentation level
(08:03:20) [ERROR @ minqlx.log_exception] Traceback (most recent call last):
(08:03:20) [ERROR @ minqlx.log_exception]   File "minqlx.zip/minqlx/_core.py", line 338, in load_plugin
(08:03:20) [ERROR @ minqlx.log_exception]     module = importlib.import_module("{}.{}".format(plugins_dir, plugin))
(08:03:20) [ERROR @ minqlx.log_exception]   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
(08:03:20) [ERROR @ minqlx.log_exception]     return _bootstrap._gcd_import(name[level:], package, level)
(08:03:20) [ERROR @ minqlx.log_exception]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
(08:03:20) [ERROR @ minqlx.log_exception]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
(08:03:20) [ERROR @ minqlx.log_exception]   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
(08:03:20) [ERROR @ minqlx.log_exception]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
(08:03:20) [ERROR @ minqlx.log_exception]   File "<frozen importlib._bootstrap_external>", line 661, in exec_module
(08:03:20) [ERROR @ minqlx.log_exception]   File "<frozen importlib._bootstrap_external>", line 767, in get_code
(08:03:20) [ERROR @ minqlx.log_exception]   File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
(08:03:20) [ERROR @ minqlx.log_exception]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
(08:03:20) [ERROR @ minqlx.log_exception]   File "./minqlx-plugins/queue.py", line 358
(08:03:20) [ERROR @ minqlx.log_exception]     self._queue = []
(08:03:20) [ERROR @ minqlx.log_exception]                    ^
(08:03:20) [ERROR @ minqlx.log_exception] IndentationError: unindent does not match any outer indentation level
(08:03:20) [ERROR @ minqlx.log_exception] 
(08:03:20) [ERROR @ minqlx.log_exception] During handling of the above exception, another exception occurred:
(08:03:20) [ERROR @ minqlx.log_exception] 
(08:03:20) [ERROR @ minqlx.log_exception] Traceback (most recent call last):
(08:03:20) [ERROR @ minqlx.log_exception]   File "minqlx.zip/minqlx/_handlers.py", line 397, in handle_console_print
(08:03:20) [ERROR @ minqlx.log_exception]     minqlx.get_logger().debug(text.rstrip("\n"))
(08:03:20) [ERROR @ minqlx.log_exception]   File "minqlx.zip/minqlx/_core.py", line 107, in get_logger
(08:03:20) [ERROR @ minqlx.log_exception]     return logging.getLogger("minqlx")
(08:03:20) [ERROR @ minqlx.log_exception]   File "/usr/lib/python3.5/logging/__init__.py", line 1781, in getLogger
(08:03:20) [ERROR @ minqlx.log_exception]     return Logger.manager.getLogger(name)
(08:03:20) [ERROR @ minqlx.log_exception]   File "/usr/lib/python3.5/logging/__init__.py", line 1144, in getLogger
(08:03:20) [ERROR @ minqlx.log_exception]     if not isinstance(name, str):

**Comment by Melodeiro** [comment] 2016-12-17 20:05
Interesting... Probably it was downloaded wrong. It tells, that the error is at 358 line in "self._queue = []", but actually this statement is at 363 line. For the best results, i will reupload here: https://gist.githubusercontent.com/Melodeiro/d831102572430a071056b58e945bcd0a/raw/7a7e89c5cbac096a92bab0a7b5eee889a67c16f7/gistfile1.txt

**Comment by Melodeiro** [comment] 2017-08-14 13:09
Sorry for a long delay, but that issue should be fixed in the 2.7 version

**Closed as completed by Melodeiro** 2017-08-14 13:09 UTC
